name: pypu
image:
  repository: etzba/pypu
  tag: "latest"
containerPort: 5000
resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity: {}